"""Add counters to User model

Revision ID: 92951312e13c
Revises: 
Create Date: 2024-06-14 15:52:12.897892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92951312e13c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cartas_leidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cartas_recibidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linea_amarilla', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linea_azul', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('videollamadas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notas_voz_recibidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notas_voz_enviadas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('regalo_virtual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('presente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_perfil', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('adjunto_visto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comision', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('comision')
        batch_op.drop_column('adjunto_visto')
        batch_op.drop_column('video_perfil')
        batch_op.drop_column('presente')
        batch_op.drop_column('regalo_virtual')
        batch_op.drop_column('notas_voz_enviadas')
        batch_op.drop_column('notas_voz_recibidas')
        batch_op.drop_column('videollamadas')
        batch_op.drop_column('linea_azul')
        batch_op.drop_column('linea_amarilla')
        batch_op.drop_column('cartas_recibidas')
        batch_op.drop_column('cartas_leidas')

    # ### end Alembic commands ###
